@host=http://localhost:3000
@api={{host}}/api/daily-pnl
@id=68dabc58b5ecae5554842ed4

### listar
GET {{api}}

### por id
GET {{api}}/{{id}}

### crear
POST {{api}}
Content-Type: application/json

{
  "account": "DU1234567",
  "date": "2025-09-28T00:00:00.000Z",
  "realized_pnl": 150.75,
  "unrealized_pnl": -20.10
}

### actualizar
PUT {{api}}/{{id}}
Content-Type: application/json

{
  "unrealized_pnl": -10.00
}

### borrar
DELETE {{api}}/{{id}}
