# Archivo: ProdServ.http
# Descripción:
# Este archivo permite probar las operaciones GET de la API de productos y servicios.
# Se define la variable @api con la URL base de la API local.
# Cada bloque realiza una petición GET para obtener todos los productos/servicios o uno específico.
# Los resultados esperados se muestran como ejemplo debajo de cada petición.

@api = http://localhost:3000/api/instruments


GET {{api}}
###
# 



